blueprint:
  name: Smart Motion-activated Light
  description: Turn on a light when motion is detected, and only if the light is not already switched on.
  domain: automation
  author: Patrick Pellacani Mueller
  input:
    motion_entity:
      name: Motion Sensor
      description: Motion sensor deciding whether or not lights go on.
      selector:
        entity:
          multiple: true
          filter:
            - device_class: occupancy
              domain: binary_sensor
            - device_class: motion
              domain: binary_sensor
    light_entities:
      name: Light
      description: Lights to turn on.
      selector:
        entity:
          multiple: true
          filter:
            - domain: light
    no_motion_wait:
      name: Wait time
      description: Time to leave the light on after last motion is detected.
      default:
        hours: 00
        minutes: 00
        seconds: 30
      selector:
        duration:

mode: single
max_exceeded: silent

triggers:
  - trigger: state
    entity_id: !input motion_entity
    from: "off"
    to: "on"

variables:
  to_turn_off: []

actions:
  - repeat:
      for_each: !input light_entities
      sequence:
        - if:
            - condition: template
              value_template: "{{ is_state(repeat.item, 'off') }}"
          then:
            - action: light.turn_on
              target:
                entity_id: "{{ repeat.item }}"
            - variables:
                to_turn_off: "{{ to_turn_off + [repeat.item] }}"
  - wait_for_trigger:
    - trigger: state
      entity_id: !input motion_entity
      from: "on"
      to: "off"
      for: !input no_motion_wait
  - repeat:
      for_each: "{{ to_turn_off }}"
      sequence:
        - action: light.turn_off
          target:
            entity_id: "{{ repeat.item }}"
