blueprint:
  name: Light Syncing
  description: Turn a light on based on another's state, keeping them in sync
  domain: automation
  author: Patrick Pellacani Mueller
  homeassistant:
    min_version: 2024.6.0
  input:
    lights:
      name: Lights
      icon: mdi:lightbulb
      input:
        source_light:
          name: Source Lights
          description: The lights from which state is taken from
          selector:
            entity:
              filter:
                - domain: light
        target_light:
          name: Target Lights
          description: Lights to keep in sync with the source light
          selector:
            target:
              entity:
                - domain: light


triggers:
  - trigger: state
    entity_id: !input source_light
    to: "off"
    id: "off"
  - trigger: state
    entity_id: !input source_light
    to: "on"
    id: "on"


actions:
  - action: >
      {% if trigger.id == "on" %}
        light.turn_on
      {% else %}
        light.turn_off
      {% endif %}
    target: !input target_light
